/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAccountRouteImport } from './routes/_site/account'
import { Route as SiteBoardsRouteImport } from './routes/_site/boards'
import { Route as SiteBountiesRouteImport } from './routes/_site/bounties'
import { Route as SiteIntelRouteImport } from './routes/_site/intel'
import { Route as SiteLoginRouteImport } from './routes/_site/login'
import { Route as SitePlayRouteImport } from './routes/_site/play'
import { Route as SiteRosterRouteImport } from './routes/_site/roster'
import { Route as SiteRulesRouteImport } from './routes/_site/rules'
import { Route as SiteSeasonRouteImport } from './routes/_site/season'
import { Route as SiteReceiptRouteImport } from './routes/_site/receipt'
import { Route as SiteShopRouteImport } from './routes/_site/shop'
import { Route as SiteWorldRouteImport } from './routes/_site/world'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as SiteRosterIgnRouteImport } from './routes/_site/roster.$ign'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiShopStatusRouteImport } from './routes/api/shop/status'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiInternalCoinGrantsPendingRouteImport } from './routes/api/internal/coin-grants/pending'
import { Route as ApiInternalCoinGrantsIdClaimRouteImport } from './routes/api/internal/coin-grants/$id.claim'
import { Route as ApiInternalCoinGrantsIdDeliveredRouteImport } from './routes/api/internal/coin-grants/$id.delivered'
import { Route as ApiInternalCoinGrantsIdReleaseRouteImport } from './routes/api/internal/coin-grants/$id.release'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAccountRoute = SiteAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBoardsRoute = SiteBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBountiesRoute = SiteBountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIntelRoute = SiteIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SitePlayRoute = SitePlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRosterRoute = SiteRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRulesRoute = SiteRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSeasonRoute = SiteSeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReceiptRoute = SiteReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopRoute = SiteShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWorldRoute = SiteWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => SiteRoute,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRosterIgnRoute = SiteRosterIgnRouteImport.update({
  id: '/$ign',
  path: '/$ign',
  getParentRoute: () => SiteRosterRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopStatusRoute = ApiShopStatusRouteImport.update({
  id: '/api/shop/status',
  path: '/api/shop/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCoinGrantsPendingRoute =
  ApiInternalCoinGrantsPendingRouteImport.update({
    id: '/api/internal/coin-grants/pending',
    path: '/api/internal/coin-grants/pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalCoinGrantsIdClaimRoute =
  ApiInternalCoinGrantsIdClaimRouteImport.update({
    id: '/api/internal/coin-grants/$id/claim',
    path: '/api/internal/coin-grants/$id/claim',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalCoinGrantsIdDeliveredRoute =
  ApiInternalCoinGrantsIdDeliveredRouteImport.update({
    id: '/api/internal/coin-grants/$id/delivered',
    path: '/api/internal/coin-grants/$id/delivered',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalCoinGrantsIdReleaseRoute =
  ApiInternalCoinGrantsIdReleaseRouteImport.update({
    id: '/api/internal/coin-grants/$id/release',
    path: '/api/internal/coin-grants/$id/release',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/account': typeof SiteAccountRoute
  '/boards': typeof SiteBoardsRoute
  '/bounties': typeof SiteBountiesRoute
  '/intel': typeof SiteIntelRoute
  '/login': typeof SiteLoginRoute
  '/play': typeof SitePlayRoute
  '/roster': typeof SiteRosterRouteWithChildren
  '/receipt': typeof SiteReceiptRoute
  '/rules': typeof SiteRulesRoute
  '/season': typeof SiteSeasonRoute
  '/shop': typeof SiteShopRoute
  '/world': typeof SiteWorldRoute
  '/api/live': typeof ApiLiveRoute
  '/roster/$ign': typeof SiteRosterIgnRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shop/status': typeof ApiShopStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/internal/coin-grants/pending': typeof ApiInternalCoinGrantsPendingRoute
  '/api/internal/coin-grants/$id/claim': typeof ApiInternalCoinGrantsIdClaimRoute
  '/api/internal/coin-grants/$id/delivered': typeof ApiInternalCoinGrantsIdDeliveredRoute
  '/api/internal/coin-grants/$id/release': typeof ApiInternalCoinGrantsIdReleaseRoute
}
export interface FileRoutesByTo {
  '/account': typeof SiteAccountRoute
  '/boards': typeof SiteBoardsRoute
  '/bounties': typeof SiteBountiesRoute
  '/intel': typeof SiteIntelRoute
  '/login': typeof SiteLoginRoute
  '/play': typeof SitePlayRoute
  '/roster': typeof SiteRosterRouteWithChildren
  '/receipt': typeof SiteReceiptRoute
  '/rules': typeof SiteRulesRoute
  '/season': typeof SiteSeasonRoute
  '/shop': typeof SiteShopRoute
  '/world': typeof SiteWorldRoute
  '/api/live': typeof ApiLiveRoute
  '/': typeof SiteIndexRoute
  '/roster/$ign': typeof SiteRosterIgnRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shop/status': typeof ApiShopStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/internal/coin-grants/pending': typeof ApiInternalCoinGrantsPendingRoute
  '/api/internal/coin-grants/$id/claim': typeof ApiInternalCoinGrantsIdClaimRoute
  '/api/internal/coin-grants/$id/delivered': typeof ApiInternalCoinGrantsIdDeliveredRoute
  '/api/internal/coin-grants/$id/release': typeof ApiInternalCoinGrantsIdReleaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/account': typeof SiteAccountRoute
  '/_site/boards': typeof SiteBoardsRoute
  '/_site/bounties': typeof SiteBountiesRoute
  '/_site/intel': typeof SiteIntelRoute
  '/_site/login': typeof SiteLoginRoute
  '/_site/play': typeof SitePlayRoute
  '/_site/receipt': typeof SiteReceiptRoute
  '/_site/roster': typeof SiteRosterRouteWithChildren
  '/_site/rules': typeof SiteRulesRoute
  '/_site/season': typeof SiteSeasonRoute
  '/_site/shop': typeof SiteShopRoute
  '/_site/world': typeof SiteWorldRoute
  '/api/live': typeof ApiLiveRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/roster/$ign': typeof SiteRosterIgnRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/shop/status': typeof ApiShopStatusRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/internal/coin-grants/pending': typeof ApiInternalCoinGrantsPendingRoute
  '/api/internal/coin-grants/$id/claim': typeof ApiInternalCoinGrantsIdClaimRoute
  '/api/internal/coin-grants/$id/delivered': typeof ApiInternalCoinGrantsIdDeliveredRoute
  '/api/internal/coin-grants/$id/release': typeof ApiInternalCoinGrantsIdReleaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/boards'
    | '/bounties'
    | '/intel'
    | '/login'
    | '/play'
    | '/receipt'
    | '/roster'
    | '/rules'
    | '/season'
    | '/shop'
    | '/world'
    | '/api/live'
    | '/roster/$ign'
    | '/api/auth/$'
    | '/api/shop/status'
    | '/api/stripe/webhook'
    | '/api/internal/coin-grants/pending'
    | '/api/internal/coin-grants/$id/claim'
    | '/api/internal/coin-grants/$id/delivered'
    | '/api/internal/coin-grants/$id/release'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/boards'
    | '/bounties'
    | '/intel'
    | '/login'
    | '/play'
    | '/receipt'
    | '/roster'
    | '/rules'
    | '/season'
    | '/shop'
    | '/world'
    | '/api/live'
    | '/'
    | '/roster/$ign'
    | '/api/auth/$'
    | '/api/shop/status'
    | '/api/stripe/webhook'
    | '/api/internal/coin-grants/pending'
    | '/api/internal/coin-grants/$id/claim'
    | '/api/internal/coin-grants/$id/delivered'
    | '/api/internal/coin-grants/$id/release'
  id:
    | '__root__'
    | '/_site'
    | '/_site/account'
    | '/_site/boards'
    | '/_site/bounties'
    | '/_site/intel'
    | '/_site/login'
    | '/_site/play'
    | '/_site/receipt'
    | '/_site/roster'
    | '/_site/rules'
    | '/_site/season'
    | '/_site/shop'
    | '/_site/world'
    | '/api/live'
    | '/_site/'
    | '/_site/roster/$ign'
    | '/api/auth/$'
    | '/api/shop/status'
    | '/api/stripe/webhook'
    | '/api/internal/coin-grants/pending'
    | '/api/internal/coin-grants/$id/claim'
    | '/api/internal/coin-grants/$id/delivered'
    | '/api/internal/coin-grants/$id/release'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  ApiLiveRoute: typeof ApiLiveRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiShopStatusRoute: typeof ApiShopStatusRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiInternalCoinGrantsPendingRoute: typeof ApiInternalCoinGrantsPendingRoute
  ApiInternalCoinGrantsIdClaimRoute: typeof ApiInternalCoinGrantsIdClaimRoute
  ApiInternalCoinGrantsIdDeliveredRoute: typeof ApiInternalCoinGrantsIdDeliveredRoute
  ApiInternalCoinGrantsIdReleaseRoute: typeof ApiInternalCoinGrantsIdReleaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/account': {
      id: '/_site/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof SiteAccountRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/boards': {
      id: '/_site/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof SiteBoardsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/bounties': {
      id: '/_site/bounties'
      path: '/bounties'
      fullPath: '/bounties'
      preLoaderRoute: typeof SiteBountiesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/intel': {
      id: '/_site/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof SiteIntelRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/play': {
      id: '/_site/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof SitePlayRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/roster': {
      id: '/_site/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof SiteRosterRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/rules': {
      id: '/_site/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof SiteRulesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/season': {
      id: '/_site/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SiteSeasonRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/receipt': {
      id: '/_site/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof SiteReceiptRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop': {
      id: '/_site/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof SiteShopRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/world': {
      id: '/_site/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof SiteWorldRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/roster/$ign': {
      id: '/_site/roster/$ign'
      path: '/$ign'
      fullPath: '/roster/$ign'
      preLoaderRoute: typeof SiteRosterIgnRouteImport
      parentRoute: typeof SiteRosterRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/status': {
      id: '/api/shop/status'
      path: '/api/shop/status'
      fullPath: '/api/shop/status'
      preLoaderRoute: typeof ApiShopStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/coin-grants/pending': {
      id: '/api/internal/coin-grants/pending'
      path: '/api/internal/coin-grants/pending'
      fullPath: '/api/internal/coin-grants/pending'
      preLoaderRoute: typeof ApiInternalCoinGrantsPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/coin-grants/$id/claim': {
      id: '/api/internal/coin-grants/$id/claim'
      path: '/api/internal/coin-grants/$id/claim'
      fullPath: '/api/internal/coin-grants/$id/claim'
      preLoaderRoute: typeof ApiInternalCoinGrantsIdClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/coin-grants/$id/delivered': {
      id: '/api/internal/coin-grants/$id/delivered'
      path: '/api/internal/coin-grants/$id/delivered'
      fullPath: '/api/internal/coin-grants/$id/delivered'
      preLoaderRoute: typeof ApiInternalCoinGrantsIdDeliveredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/coin-grants/$id/release': {
      id: '/api/internal/coin-grants/$id/release'
      path: '/api/internal/coin-grants/$id/release'
      fullPath: '/api/internal/coin-grants/$id/release'
      preLoaderRoute: typeof ApiInternalCoinGrantsIdReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRosterRouteChildren {
  SiteRosterIgnRoute: typeof SiteRosterIgnRoute
}

const SiteRosterRouteChildren: SiteRosterRouteChildren = {
  SiteRosterIgnRoute: SiteRosterIgnRoute,
}

const SiteRosterRouteWithChildren = SiteRosterRoute._addFileChildren(
  SiteRosterRouteChildren,
)

interface SiteRouteChildren {
  SiteAccountRoute: typeof SiteAccountRoute
  SiteBoardsRoute: typeof SiteBoardsRoute
  SiteBountiesRoute: typeof SiteBountiesRoute
  SiteIntelRoute: typeof SiteIntelRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SitePlayRoute: typeof SitePlayRoute
  SiteReceiptRoute: typeof SiteReceiptRoute
  SiteRosterRoute: typeof SiteRosterRouteWithChildren
  SiteRulesRoute: typeof SiteRulesRoute
  SiteSeasonRoute: typeof SiteSeasonRoute
  SiteShopRoute: typeof SiteShopRoute
  SiteWorldRoute: typeof SiteWorldRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAccountRoute: SiteAccountRoute,
  SiteBoardsRoute: SiteBoardsRoute,
  SiteBountiesRoute: SiteBountiesRoute,
  SiteIntelRoute: SiteIntelRoute,
  SiteLoginRoute: SiteLoginRoute,
  SitePlayRoute: SitePlayRoute,
  SiteReceiptRoute: SiteReceiptRoute,
  SiteRosterRoute: SiteRosterRouteWithChildren,
  SiteRulesRoute: SiteRulesRoute,
  SiteSeasonRoute: SiteSeasonRoute,
  SiteShopRoute: SiteShopRoute,
  SiteWorldRoute: SiteWorldRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  ApiLiveRoute: ApiLiveRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiShopStatusRoute: ApiShopStatusRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiInternalCoinGrantsPendingRoute: ApiInternalCoinGrantsPendingRoute,
  ApiInternalCoinGrantsIdClaimRoute: ApiInternalCoinGrantsIdClaimRoute,
  ApiInternalCoinGrantsIdDeliveredRoute: ApiInternalCoinGrantsIdDeliveredRoute,
  ApiInternalCoinGrantsIdReleaseRoute: ApiInternalCoinGrantsIdReleaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
